# Generated by Django 2.2.9 on 2022-12-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221217_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='discription',
            new_name='description',
        ),
    ]
